mailer:
  domain: <%= ENV['SMTP_DOMAIN'] %>
  from: <%= ENV['DEFAULT_FROM_EMAIL'] %>
  username: <%= ENV['SMTP_USER_NAME'] %>
  password: <%= ENV['SMTP_PASSWORD'] %>
  host: <%= ENV['HOST'] %>
google:
 maps_api:
  key: AIzaSyC0LhT2ttkS1GSsAV6mNoW_vQyi0L4RZMk