mailer:
  domain: 'botreetechnologies.com'
  from: 'botreetechnologies@gmail.com'
  username: 'botreetechnologies@gmail.com'
  password: 'botreetester'
google:
 maps_api:
  key: AIzaSyC0LhT2ttkS1GSsAV6mNoW_vQyi0L4RZMk